Add demo for ViewItemDelegate class added to tk-framework-qtwidgets
shotgunsoftware/tk-multi-demo pull request #16
Opened 2021-04-14 19:29 UTC by staceyoue

2021-09-09 22:40 UTC, staceyoue commented on python/tk_multi_demo/demos/view_item_delegate/ui/resources_rc.py
> +qInitResources()
This file is autogenerated

2021-09-09 22:41 UTC, staceyoue commented on python/tk_multi_demo/demos/view_item_delegate/ui/resources_rc.py
> +def qCleanupResources():
Ignoring -- this file is autogenerated

2021-09-09 22:41 UTC, staceyoue commented on python/tk_multi_demo/demos/view_item_delegate/ui/resources_rc.py
> +def qInitResources():
Ignoring -- this file is autogenerated

2021-09-09 22:42 UTC, staceyoue commented on python/tk_multi_demo/demos/view_item_delegate/__init__.py
> +from .demo import ViewItemDelegateDemo
We need this for the demo to be discoverable

2021-09-28 14:18 UTC, mathurf requested changes
Please fix code style validation issues (Black) by running pre-commit locally

2021-09-28 14:28 UTC, mathurf approved these changes
LGTM

2021-09-30 14:45 UTC, 000paradox000 approved these changes

2021-09-30 15:08 UTC, merged