SG-33500 New build resources yml
shotgunsoftware/tk-multi-demo pull request #42
Opened 2024-07-31 04:41 UTC by eduardoChaucaGallegos

- New build resources yml

2024-07-31 16:22 UTC, julien-lang reviewed
Looks good. Just a couple minor points before I approve

2024-07-31 16:22 UTC, julien-lang commented on build_resources.yml
> +# https://github.com/shotgunsoftware/tk-toolchain?tab=readme-ov-file#tk-build-qt-resources.
```suggestion
# YAML Configuration File for Qt Resource Building
#
# For more information: https://github.com/shotgunsoftware/tk-toolchain/blob/master/README.md#tk-build-qt-resources
```

2024-07-31 16:22 UTC, julien-lang commented on build_resources.yml
> +  import_pattern: tank.platform.qt
Remove default values if https://github.com/shotgunsoftware/tk-toolchain/pull/65#discussion_r1698774692 is approved

2024-07-31 23:49 UTC, julien-lang approved these changes

2024-08-01 14:22 UTC, julien-lang approved these changes

2024-09-05 20:31 UTC, carlos-villavicencio-adsk requested changes

2024-09-05 20:31 UTC, carlos-villavicencio-adsk commented on python/tk_multi_demo/demos/screen_capture_widget/ui/screen_capture_widget_demo.py
> +while executing 'c:\users\chaucae\documents\projects\tk-core\.venv\lib\site-packages\PySide2\uic -g python -g python --from-imports C:\Users\chaucae\Documents\projects\tk-multi-demo\python\tk_multi_d
These are causing syntax errors.

2024-09-06 02:46 UTC, carlos-villavicencio-adsk approved these changes
LGTM

2024-09-07 00:38 UTC, merged